MRSapp/urls.py
from django.urls import path

from MRSapp import views

app_name = 'mrs_app'

urlpatterns = [
    path('', views.index, name='search'),
]

MovieRecommendationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('MRSapp.urls', namespace='mrs_app')),
    path('', include('accounts.urls', namespace='authentication')),
]

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
]

MRSapp/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, widget=forms.EmailInput
                            (attrs={'placeholder': 'Email Address',
                             'class': 'input100', 'required': ''}))
    password1 = forms.CharField(max_length=254, widget=forms.PasswordInput
                               (attrs={'placeholder': 'Password',
                                'class': 'input100', 'required': ''}))
    password2 = forms.CharField(max_length=254, widget=forms.PasswordInput
                               (attrs={'placeholder': 'Confirm Password',
                                'class': 'input100', 'required': ''}))

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'password1', 'password2',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

MRSapp/views.py
from django.shortcuts import render, redirect
import pickle
import os
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from django.contrib import messages
from django.core import serializers

# Create your views here.

# importing metadata dataset
df_clean=pd.read_csv("metadata_clean.csv")
# importing movies_metadata
df_meta=pd.read_csv("movies_metadata.csv")#error_bad_lines=False
#df_meta.head()
df_clean['overview'], df_clean['id'] = df_meta['overview'], df_meta['id']

#df_clean.head()
df_clean=df_clean.iloc[:10000]

# define TF IDF Vestorizer object,remove all english stopword
tfidf=TfidfVectorizer(stop_words="english")
df_clean["overview"]=df_clean["overview"].fillna('')
# constructing IF-IDF Matrix by applying fit_transform mathed on overview feature
tfidf_matrix=tfidf.fit_transform(df_clean["overview"])

# compute the cosine similarity matrix
cosine_sim=linear_kernel(tfidf_matrix,tfidf_matrix)
#Construct a reverse mapping of indices and movie titles, and drop duplicate titles, if any
indices = pd.Series(df_clean.index, index=df_clean['title']).drop_duplicates()
n = False
# Function that takes in movie title as input and gives recommendations 
def content_recommender(title, cosine_sim=cosine_sim, df_clean=df_clean, indices=indices):
    # Obtain the index of the movie that matches the title
    global n
    # print(title)
    try:
        # print(bool(indices[title]))
        idx = indices[title]
        # print(idx)
        n = True
    except KeyError:
        n = False
        return n
    # Get the pairwsie similarity scores of all movies with that movie
    # And convert it into a list of tuples as described above
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    # Sort the movies based on the cosine similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies. Ignore the first movie.
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df_clean['title'].iloc[movie_indices]
    
# pickle.dump(content_recommender, open('mypickmodel.pkl','wb'))
# Loading model to compare the results

modulePath = os.path.dirname(__file__)
filePath = os.path.join(modulePath,'mypickmodel.pkl')
model = pickle.load(open('mypickmodel.pkl','rb'))

# def index(request):
#     if request.method=="POST":
#         a = request.POST['movie']
#         o = model(a)
#         o = serializers.serialize('xml', o)
#         return HttpResponse(o, content_type="application/xml")
#     return render(request,'index.html')



def index(request):
    if request.method=="POST":
        a = request.POST['movie']
        #Get recommendations for The Lion King
        #content_recommender("The Lion King")
        output = model(a)
        # print(np.dtype(output))
        # print(bool(output))
        if n:
            # print('yes')
            return render(request,'index.html',{'output':output})
            
        else:
            # print('no')
            messages.info(request,'We don\'t have this movie')
            return redirect('index')
    return render(request,'index.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from accounts.decorators import unauthenticated_user
from accounts.forms import CustomUserCreationForm


@unauthenticated_user
def home(request):
	context = {}
	return render(request, 'home.html', context)


@unauthenticated_user
def register(request):
	form = CustomUserCreationForm()
	if request.method == 'POST':
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.cleaned_data.get('email')
			form.save()
			messages.success(request, 'Account was created for ' + user)
			return redirect('authentication:login')
	context = {'form': form}
	return render(request, 'register.html', context)


@unauthenticated_user
def login_page(request):
	if request.method == 'POST':
		email = request.POST['email']
		password = request.POST['password']

		user = authenticate(request, email=email, password=password)

		if user is not None:
			login(request, user)
			return redirect('mrs_app:search')
		else:
			messages.info(request, 'Username or password is incorrect')

	context = {}
	return render(request, 'login.html', context)


def logout_page(request):
	logout(request)
	return redirect('/')

accounts/templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title_block %} {% endblock title_block %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		{% block custom_css %} {% endblock custom_css %}
	</head>
	<body>
		{% block body_block %} {% endblock body_block %}

		<script src="{% static 'js/main.js' %}"></script>
		{% block custom_js %} {% endblock custom_js %}
	</body>
</html>

accounts/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title_block %} Home {% endblock title_block %}

{% block custom_css %}
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
{% endblock custom_css %}

{% block body_block %}

<!-- Header -->
	<header id="header">
		<div class="inner">
			<a href="{% url 'authentication:home' %}" class="logo">MRS</a>
			<!-- <nav id="nav">
				<a href="#">Home</a>
				<a href="#">Generic</a>
				<a href="#">Elements</a>
			</nav> -->
			<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
		</div>
	</header>

<!-- Banner -->
	<section id="banner">
		<h1>Welcome to Movie Recommendation System</h1>
		<!-- <p>A free responsive HTML5 website template by TEMPLATED.</p> -->
	</section>

<!-- One -->
	<section id="one" class="wrapper">
		<div class="inner">
			<div class="flex flex-2">
				<article>
					<header>
						<h3>If you're new user,<br /> Sign Up</h3>
					</header>
					<!-- <p>Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, lectus arcu.</p> -->
					<footer>
						<a href="{% url 'authentication:register' %}" class="button special">Sign Up</a>
					</footer>
				</article>
				<article>
					<header>
						<h3>If you're already a user,<br /> Log In</h3>
					</header>
					<!-- <p>Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, lectus arcu.</p> -->
					<footer>
						<a href="{% url 'authentication:login' %}" class="button special">Log In</a>
					</footer>
				</article>
			</div>
		</div>
	</section>

<!-- Footer -->
	<footer id="footer">
		<div class="inner">
			<div class="flex">
				<div class="copyright">
					&copy; 2020.
				</div>
				<!-- <ul class="icons">
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-linkedin"><span class="label">linkedIn</span></a></li>
					<li><a href="#" class="icon fa-pinterest-p"><span class="label">Pinterest</span></a></li>
					<li><a href="#" class="icon fa-vimeo"><span class="label">Vimeo</span></a></li>
				</ul> -->
			</div>
		</div>
	</footer>

{% endblock body_block %}

{% block custom_js %}
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/skel.min.js' %}"></script>
	<script src="{% static 'js/util.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
{% endblock custom_js %}

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title_block %} Login {% endblock title_block %}

{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main-login.css' %}">
{% endblock custom_css %}

{% block body_block %}

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST" action="{% url 'authentication:login' %}">
					{% csrf_token %}
					<span class="login100-form-title">
						Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email or Phone Number" required>
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password" required>
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					{% for message in messages %}
						<span class="messages">{{ message }}</span>
					{% endfor %}
					<!-- <div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div> -->

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'authentication:register' %}">
							Signup
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>

			</div>
		</div>
	</div>
{% endblock body_block %}

{% block custom_js %} 
<!--===============================================================================================-->	
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
{% endblock custom_js %}

accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block title_block %} Register {% endblock title_block %}

{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main-login.css' %}">
{% endblock custom_css %}

{% block body_block %}

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="POST" action="{% url 'authentication:register' %}">
					{% csrf_token %}
					<span class="login100-form-title">
						Signup
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<!-- <input class="input100" type="text" name="email" placeholder="Email"> -->
						{{ form.email }}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						{{ form.password1 }}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						{{ form.password2 }}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<!-- <div class="wrap-input100 validate-input" data-validate = "Password is required">
						{{ form.password1 }}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div> -->
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign Up
						</button>
					</div>

					{% for error in form.errors %}
					<div class="text-center p-t-12">
						{{ error }}
					</div>
					{% endfor %}
					
					<!-- <div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div> -->

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'authentication:login' %}">
							Login
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock body_block %}

{% block custom_js %} 
<!--===============================================================================================-->	
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
{% endblock custom_js %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> 
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a class="btn" href="{% url 'authentication:logout' %}">Logout</a>
    {% endif %}

    <!-- <div class="bg-image"></div> -->
    <div class="slideshow-container">

        <div class="mySlides fade">
            <img src="{% static 'images/rm.jpeg' %}" style="width:100%">
        </div>
        
        <div class="mySlides fade">
            <img src="{% static 'images/rr.jpeg' %}" style="width:100%">
        </div>
        
        <div class="mySlides fade">
            <img src="{% static 'images/try.jpeg' %}" style="width:100%">
        </div>
        
    </div>
    <div class="bg-text">
        <div class='row align-items-start mt-4'>
            <form action="{% url 'mrs_app:search' %}" method="post">
                {% csrf_token %}
                <div class="form-group mx-sm-3 mb-2">
                    <input type="text" name='movie' class="form-control" placeholder="Enter Movie Name"><br>
                    <input type="submit" value="Search Movie">
                </div>
            </form>
        
        <div class='row align-items-end no-gutters'>
            {% if messages %}
                {% for message in messages %}
                    <h1>{{ message }}</h1>
                {% endfor %}
            {% else %}
                {% for i in output %}
                    <div class='col-sm-6' style='color:#fff;font-size:30px'>
                        <p>{{ i }}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    </div>

<script>
    var slideIndex = 0;
    showSlides();
    
    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        
        for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
        }
        slideIndex++;
        if (slideIndex > slides.length) {slideIndex = 1}    
        
        slides[slideIndex-1].style.display = "block";  
        
        setTimeout(showSlides, 5000); // Change image every 2 seconds
    }
</script>

</body>
</html>